- config/config.js
Allow using environment variables to configure secrets.
> Add possibility to configure secrets

- src/lib/adlib.js
- src/lib/utils.js
Todo: refactor version in Adlib.prototype.run
> Log current version

- src/app.js
- src/config.tml
- src/lib/adlib.js
- src/lib/mappers/tentoonstellingMapper.js
- src/lib/mappers/termenMapper.js
fix termenmapper to fetch gender from Adlib.
> fix mapping geslacht for LDES personen + add LDES tentoonstellingen

- src/lib/mappers/utils.js
Cannot read property '0' of undefined
> Fix TypeError

- src/lib/mappers/termenMapper.js
TypeError: Cannot read property 'includes' of undefined
> 52: Fix TypeError

- src/lib/adlib.js
- startfrom (Integer) [optional] first key number to return in the result (default = 1: the first key number in an index is 1).
See https://api.adlibsoft.com/api/functions/search
> Fix paging

- src/lib/adlib.js
Instellingen logt momenteel "All objects are fetched from dmg!"
=> "All objects are fetched for tentoonstellingen from dmg!"
> Refactor logging when done

- package-lock.json
- src/lib/mappers/IndustriemuseumMapper.js
- src/lib/mappers/archiefGentMapper.js
- src/lib/mappers/dmgMapper.js
- src/lib/mappers/hvaMapper.js
- src/lib/mappers/objectMapper.js
- src/lib/mappers/stamMapper.js
- src/lib/mappers/utils.js
> add IIIF manifest mapper [update]

- src/lib/adlib.js
- src/lib/mappers/dmgMapper.js
- src/lib/mappers/objectMapper.js
- src/lib/mappers/utils.js
- src/lib/utils.js
- vervaardiger.kwalificatie
- afmeting.vrij
- associatie.onderwerp.associatie
- associatie.periode.associatie
- koepelrecord DMG
> Final mappings

- src/lib/mappers/IndustriemuseumMapper.js
- src/lib/mappers/archiefGentMapper.js
- src/lib/mappers/dmgMapper.js
- src/lib/mappers/hvaMapper.js
- src/lib/mappers/stamMapper.js
- src/lib/mappers/utils.js
add Boolean statement to choose whether techniek needs to be parsed or not.
> Boolean switch for parsing techniek. 

- src/lib/mappers/utils.js
EntiteitBeeldtuit needs to MensgemaaktObject.beeldtuit.
> fix issue: OSLO name was not correct

- src/lib/mappers/utils.js
> Fix MensgemaaktObject.beeldtuit

- src/lib/mappers/utils.js
fix property. (not in context); see also - https://github.com/StadGent/node_service_eventstream-api/pull/35/commits/d0a463d5a899c26d4190a69b82e4a31ad2861fca
gebruiktBijActiviteit --> Activiteit.gebruiktObject
"ConceptueelDing.heeftCreatie" --> ConceptueelDing.creatie
> fix mapTentoonstelling;

- src/lib/mappers/utils.js
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/Administrator/AppData/Local/Packages/microsoft.windowscommunicationsapps_8wekyb3d8bbwe/TempState/msohtmlclip/clip_filelist.xml">
<link rel=Edit-Time-Data
href="file:///C:/Users/Administrator/AppData/Local/Packages/microsoft.windowscommunicationsapps_8wekyb3d8bbwe/TempState/msohtmlclip/clip_editdata.mso">
<link rel=themeData …
> Fix opschriften en inhoud (IM): do not overwrite

- src/lib/mappers/tentoonstellingMapper.js
fix https://github.com/StadGent/node_service_eventstream-api/issues/46
> fix Mapping: items in GecureerdeCollectie.bestaatUit do not have @type

- .github/workflows/node.js.yml
- package.json
- src/app.js
- src/config.tml
- src/config/config.js
- src/lib/adlib.js
- src/lib/mappers/IndustriemuseumMapper.js
- src/lib/mappers/archiefGentMapper.js
- src/lib/mappers/dmgMapper.js
- src/lib/mappers/hvaMapper.js
- src/lib/mappers/objectMapper.js
- src/lib/mappers/stamMapper.js
- src/lib/mappers/tentoonstellingMapper.js
- src/lib/mappers/termenMapper.js
Run e2e test on first page of each institution;
> Add e2e tests

- .github/workflows/node.js.yml
Runs at 22:00, Monday through Friday.
Actions schedules run using UTC time.
> Run e2e tests on cron

- src/lib/mappers/termenMapper.js
Can't have both @value and @id.
> Fix invalid jsonld object

- src/lib/mappers/utils.js
example: https://gist.github.com/oliviervd/abec626c0d9ec099751018f5e31cbea7#file-example-json-L353
> Update utils.js - add @id for exhibitions.

- src/lib/mappers/dmgMapper.js
- src/lib/mappers/utils.js
extend mapRelatiesKoepelRecord to work more generic (not only in logic of "dossier"). Add this utils to mapper DMG
> extend mapRelatiesKoepelrecord to work for museums (apart from dossier)

- src/lib/mappers/tentoonstellingMapper.js
- src/lib/mappers/utils.js
issue with URIs, but not necessary. - commented out.
> @id title expo fix
